<?php namespace ProcessWire;

class InputfieldSimpleMarkdownEditor extends InputfieldTextarea
{
    private $baseUrl = '';
    private $basePath = '';

    public static function getModuleInfo()
    {
        return array(
            'title' => 'Simple Markdown Editor',
            'version' => '1.0.0',
            'author' => 'abdus',
            'summary' => 'Simple Markdown text editor.',
            'href' => 'https://github.com/abdusco/pw-simplemde-editor',
            'autoload' => true, // set to true if module should auto-load at boot
            'singular' => false,
            'requires' => array(
                'PHP>=5.4.1',
                'ProcessWire>=2.8'
            ),
            'installs' => array(
                'TextformatterParsedownExtraPlugin',
                'TextformatterImageFieldMarkup'
            )
        );
    }


    public function ___render()
    {
        $templatePath = $this->basePath . 'markup/simplemde.php';

        $this->config->scripts->add($this->baseUrl . 'simplemde/dist/simplemde.min.js');
        $this->config->styles->add($this->baseUrl . 'simplemde/dist/simplemde.min.css');

        $attrs = $this->getAttributes();
        unset($attrs['value'], $attrs['size'], $attrs['type']);

        return wireRenderFile($templatePath, [
            'attrs' => $this->getAttributesString($attrs),
            'value' => htmlspecialchars($this->value, ENT_QUOTES, "UTF-8"),
            'editorId' => $attrs['id'],
            'customConfig' => preg_replace('/[\n\r]/', '', $this->customConfig),
            'monospaced' => $this->monospaced
        ]);
    }


    public function init()
    {
        $this->baseUrl = $this->config->urls->get($this->className);
        $this->basePath = $this->config->paths->get($this->className);
    }


}